name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Go version to build ("1.21")'
        required: true
      prerelease:
        description: "Is this a pre-release?"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - builder: macos-latest
            goos: darwin
            goarch: arm64
          - builder: macos-latest
            goos: darwin
            goarch: amd64
          - builder: ubuntu-22.04
            goos: linux
            goarch: amd64
          - builder: ubuntu-22.04
            goos: linux
            goarch: arm64
          - builder: windows-latest
            goos: windows
            goarch: amd64
          - builder: windows-latest
            goos: windows
            goarch: arm64

    runs-on: ${{ matrix.builder }}
    outputs:
      built_version: ${{ steps.encore_go_version.outputs.version }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # We need the full history for the Go submodule
          submodules: "recursive" # Checkout the Go submodule
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true

      - name: "Create patched runtime"
        run: bash ./apply_patch.bash "${{ github.event.inputs.version }}"

      - name: Build
        run: go run . -dst=dist -goos=${{ matrix.goos }} -goarch=${{ matrix.goarch }}
        env:
          GO111MODULE: "on"

      # This step gets the exact version of Go we're releasing (including minor), so if we give the input as `1.17` this might return `encore-go1.17.5`.
      - name: "Read the version of Go we built"
        id: encore_go_version
        shell: bash
        run: |
          VERSION_OUTPUT=$(go run . --read-built-version)
          echo "version=${VERSION_OUTPUT}" >> $GITHUB_OUTPUT
          echo "Detected version: ${VERSION_OUTPUT}"

      - name: "Tar artifacts"
        shell: bash
        run: |
          VERSION="${{ steps.encore_go_version.outputs.version }}"
          GOOS="${{ matrix.goos }}"
          GOARCH="${{ matrix.goarch }}"
          ARCHIVE_NAME="${VERSION}-${GOOS}_${GOARCH}.tar.gz"
          echo "Creating artifact: ${ARCHIVE_NAME}"
          tar -czvf "${ARCHIVE_NAME}" -C "dist/${GOOS}_${GOARCH}" .
          echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        id: archive

      - name: "Upload build artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.archive.outputs.ARCHIVE_NAME }}
          path: ${{ steps.archive.outputs.ARCHIVE_NAME }}
  release:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: "Download artifacts from build steps"
        uses: actions/download-artifact@v5

      - name: "Convert windows artifacts to zip"
        run: |
          VERSION="${{needs.build.outputs.built_version}}"
          for dir in ${VERSION}-windows_*/; do
            echo "Converting ${dir} to zip..."
            cd "${dir}"
            tar -xzf *.tar.gz
            basename=$(basename "${dir}")
            zip -r "${basename}.zip" encore-go
            cd ..
          done

      - name: "Move, rename and create checksums for the artifacts"
        run: |
          mkdir output
          VERSION="${{needs.build.outputs.built_version}}"

          for dir in ${VERSION}-*/; do
            cd "${dir}"
            for file in *.tar.gz *.zip; do
              if [ -f "${file}" ]; then
                basename="${file#${VERSION}-}"
                mv "${file}" "../output/${basename}"
              fi
            done
            cd ..
          done

          cd output
          sha256sum * > checksums.txt
          ls -R .
          mv * ../
          cd ..
          cat checksums.txt

      - name: "Publish release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.built_version }}
          name: ${{ needs.build.outputs.built_version }}
          body: |
            This release is the compiled version of ${{ needs.build.outputs.built_version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            *.tar.gz
            *.zip
            checksums.txt
